run:
  skip-files:
    - test\.go

linters-settings:
  govet:
    check-shadowing: true
  misspell:
    locale: US
  dupl:
    threshold: 150
  nestif:
    min-complexity: 5
  forbidigo:
    forbid:
      - 'fmt\.Print.*'
  tagliatelle:
    case:
      rules:
        # support string case: `camel`, `pascal`, `kebab`, `snake`, `goCamel`, `goPascal`, `goKebab`, `goSnake`, `upper`, `lower`
        json: snake
        yaml: camel
        xml: camel

linters:
  disable-all: true
  enable:
    - revive
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - structcheck
    - varcheck
    - ineffassign
    - unused
    - deadcode
    - typecheck
    - stylecheck
    - gosec
    - gofmt
    - goimports
    - misspell
    - unparam
    - wastedassign
    - prealloc
    - unconvert
    - wsl
    - nilerr
    - predeclared
    - nestif
    - nilnil
    - bodyclose
    - dupl
    - contextcheck
    - durationcheck
    - errorlint
    - exportloopref
    - forbidigo
    - forcetypeassert
    - funlen
    - goconst
    - ifshort
    - tagliatelle
    - thelper
    - whitespace
