version: '3.9'

services:
  oapi-codegen:
    build:
      context: oapi-generator
      dockerfile: Dockerfile
    volumes:
      - ./application:/go/src/app/application
      - ./domain:/go/src/app/domain
    command: >
      bash -c 'oapi-codegen -generate types,spec,skip-prune -package model param.yaml > application/api/params/param.gen.go && \
              oapi-codegen -generate spec -package api -import-mapping=./param.yaml:github.com/caravan-inc/fankey-server/application/api/params openapi.yaml > application/api/spec.types.gen.go && \
              oapi-codegen -generate types -package pet -include-tags=pet -import-mapping=./param.yaml:github.com/caravan-inc/fankey-server/application/api/params openapi.yaml > application/api/pet/pet.types.gen.go && \
              oapi-codegen -templates template -generate chi-server -package pet -include-tags=pet -import-mapping=./param.yaml:github.com/caravan-inc/fankey-server/application/api/params openapi.yaml > application/api/pet/pet.server.gen.go && \
              oapi-codegen -generate types -package user -include-tags=user -import-mapping=./param.yaml:github.com/caravan-inc/fankey-server/application/api/params openapi.yaml > application/api/user/user.types.gen.go && \
              oapi-codegen -templates template -generate chi-server -package user -include-tags=user -import-mapping=./param.yaml:github.com/caravan-inc/fankey-server/application/api/params openapi.yaml > application/api/user/user.server.gen.go'

  sqlboiler:
    build:
      context: tools/sqlboiler
      dockerfile: Dockerfile
    working_dir: /worker
    volumes:
      - ./tools/sqlboiler/sqlboiler.toml:/worker/sqlboiler.toml
      - ./domain/model:/worker/domain/model
    networks:
      - mysql-network
    command: mysql

  mysql:
    image: mysql:8.0.27
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    restart: always
    networks:
      - mysql-network

  create:
    image: mysql:8.0.27
    volumes:
      - ./ddl:/tmp/ddl
    command: bash -c 'mysql -hmysql -uuser -ppassword db < /tmp/ddl/schema.sql'
    networks:
      - mysql-network

  cli:
    image: mysql:8.0.27
    networks:
      - mysql-network
    command: mysql -hmysql -uuser -ppassword db

  tbls:
    image: ghcr.io/k1low/tbls:v1.54.2
    working_dir: /worker
    volumes:
      - ./doc:/doc
      - ./tools/tbls:/worker
    networks:
      - mysql-network
    command: doc mysql://user:password@mysql:3306/db /doc/database --rm-dist

networks:
  mysql-network:
    driver: bridge
