version: "3"

tasks:
  default:
    aliases:
      - list
    desc: List all tasks
    cmd: task -l

  server:
    cmds:
      - docker compose up -d server
    desc: Start server
    silent: true

  firebase:
    cmds:
      - docker compose up -d firebase
    desc: Start firebase
    silent: true

  di:
    cmds:
      - docker compose run wire
    desc: Generate dependency injection
    silent: true

  migrate:
    cmds:
      - docker compose run migrate
    desc: Run migration
    silent: true

  gen-entity:
    cmds:
      - docker compose run sqlboiler
    desc: Generate entity
    silent: true

  faker:
    cmds:
      - docker compose run faker
    desc: Generate fake data
    silent: true

  local-user:
    cmds:
      - sh ./tools/firebase/create-local-user.sh
    desc: Create local user
    silent: true
