version: "3"

tasks:
  default:
    aliases:
      - list
    desc: List all tasks
    cmd: task -l

  di:
    cmds:
      - docker compose run wire
    desc: Generate dependency injection
    silent: true

  migrate:
    cmds:
      - docker compose run migrate
    desc: Run migration
    silent: true
