// Code generated by gogen; DO NOT EDIT.

package driver

import (
	"context"

	"github.com/HMasataka/beyond/domain/entity"
)

type AccountDriver interface {
	Insert(ctx context.Context, target *entity.Account) error
	FindByFirebaseUID(ctx context.Context, id string) (*entity.Account, error)
	Update(ctx context.Context, target *entity.Account) error
	Delete(ctx context.Context, target *entity.Account) error
}
