definitions:
  payload.Error:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
  payload.GetHealthResponse:
    type: object
host: localhost:8081
info:
  contact: {}
  description: oshi card recommendation api
  title: Oshi Card Recommendation API
  version: "1.0"
paths:
  /healthz:
    get:
      description: ヘルスチェック
      operationId: Healthz
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/payload.GetHealthResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/payload.Error'
      summary: Healthz
      tags:
      - health
swagger: "2.0"
