// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/HMasataka/beyond/config"
	"github.com/HMasataka/beyond/handler"
)

// Injectors from server.wire.go:

func InitializeServerHandler(cfg *config.Config) *handler.HandlerContainer {
	handlerContainer := handler.NewHandlerOnce()
	return handlerContainer
}
