// Code generated by gogen; DO NOT EDIT.

package driver

import (
	"context"

	"github.com/HMasataka/beyond/domain/driver"
	"github.com/HMasataka/beyond/domain/entity"
	"github.com/HMasataka/transactor/rdbms"
	"github.com/volatiletech/sqlboiler/v4/boil"
)

type userDriver struct {
	clientProvider rdbms.ClientProvider
}

func NewUserDriver(clientProvider rdbms.ClientProvider) driver.UserDriver {
	return &userDriver{
		clientProvider: clientProvider,
	}
}

func (r *userDriver) Insert(ctx context.Context, target *entity.User) error {
	client := r.clientProvider.CurrentClient(ctx)
	return target.Insert(ctx, client, boil.Infer())
}

func (r *userDriver) Find(ctx context.Context, userID string) (*entity.User, error) {
	client := r.clientProvider.CurrentClient(ctx)

	user, err := entity.Users(entity.UserWhere.ID.EQ(userID)).One(ctx, client)
	if wrapError(err) != nil {
		return nil, err
	}

	return user, nil
}

func (r *userDriver) Update(ctx context.Context, target *entity.User) error {
	client := r.clientProvider.CurrentClient(ctx)
	_, err := target.Update(ctx, client, boil.Infer())

	return err
}

func (r *userDriver) Delete(ctx context.Context, target *entity.User) error {
	client := r.clientProvider.CurrentClient(ctx)
	_, err := target.Delete(ctx, client)

	return err
}
