name: migration

on:
  push:
    branches:
      - main
    paths:
      - '**.go'
  pull_request:
    paths:
      - '**.go'

jobs:
  lint:
    name: golangci-lint
    runs-on: ubuntu-18.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.44
