name: migration

on:
  push:
    branches:
      - main
    paths:
      - 'ddl/**'
  pull_request:
    paths:
      - 'ddl/**'

jobs:
  mysql8_0:
    name: mysql_migration_test
    runs-on: ubuntu-18.04
    services:
      mysql:
        image: mysql:8.0.27
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: db
          MYSQL_USER: user
          MYSQL_PASSWORD: password
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: download migration tool
        run: curl -L https://github.com/golang-migrate/migrate/releases/download/v4.15.1/migrate.linux-amd64.tar.gz | tar xvz -C /opt

      - name: migration up
        run: /opt/migrate -path ddl -database mysql://user:password@tcp\(localhost:3306\)/db up

      - name: generate db document
        uses: docker://ghcr.io/k1low/tbls:v1.54.2
        with:
          args: doc mysql://user:password@mysql:3306/db doc/database --rm-dist

      - name: migration down
        run: /opt/migrate -path ddl -database mysql://user:password@tcp\(localhost:3306\)/db down -all

      - name: Count changes
        run: |
          echo "$(git status)"

      - name: Count changes
        id: changes
        run: |
          git add -N .
          echo "::set-output name=count::$(git diff --name-only | wc -l)"

      - name: echo count
        if: steps.changes.outputs.count > 0
        run: echo "The count = ${{ steps.changes.outputs.count }}"
