name: migration

on:
  push:
    branches:
      - main
    paths:
      - 'ddl/**'
  pull_request:
    paths:
      - 'ddl/**'

jobs:
  mysql8_0:
    name: mysql_migration_test
    runs-on: ubuntu-18.04
    services:
      mysql:
        image: mysql:8.0.27
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: db
          MYSQL_USER: user
          MYSQL_PASSWORD: password
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: download migration tool
        run: curl -L https://github.com/golang-migrate/migrate/releases/download/v4.15.1/migrate.linux-amd64.tar.gz | tar xvz
      - name: migration up
        run: ./migrate -path ddl -database mysql://user:password@tcp\(localhost:3306\)/db up
      - name: migration down
        run: ./migrate -path ddl -database mysql://user:password@tcp\(localhost:3306\)/db down -all
